server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: hict-kafka-1:9092,hict-kafka-2:9092
    client-id: 'scheduler'
    consumer:
      group-id: 'hict'
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
