{
 "title": "HiCT",
 "description": "HiCT Platform dashboard",
 "tags": [
  "hict",
  "logging"
 ],
 "time": { "from": "now-5d", "to": "now" },
 "panels": [
  {
   "title": "Title",
   "type": "text",
   "description": "Title",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">HiCT Platform</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Project version",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "PostgreSQL version",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "MinIO version",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "NGINX version",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "type": "yesoreyeram-boomtheme-panel", "description": "Themes", "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 } },
  { "title": "Authorization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Authorization logs",
   "type": "logs",
   "description": "Authorization logs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"authorization-logs\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Authorization server attendance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({jobs=\"authorization-logs\"}[1h])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Authorization logs errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({jobs=\"authorization-logs\"} | level = `ERROR` [1h])"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Users",
   "type": "table",
   "description": "List of users",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select users.id, users.username, users.role\r\nfrom users ;"
    }
   ]
  },
  {
   "title": "User roles",
   "type": "piechart",
   "description": "User roles pie chart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select users.role, count(users.id)\r\nfrom users\r\ngroup by users.role ;"
    }
   ]
  },
  {
   "title": "New users",
   "type": "timeseries",
   "description": "New users history",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 24 },
   "targets": [
    {
     "rawSql": "select by_date.date_time, count(by_date.id)\r\nfrom (select users.id, date_trunc('day', creation_time) as date_time\r\n      from users) by_date\r\ngroup by by_date.date_time ;\r\n\r\n-- select $__timeGroup(creation_time, 1d), count(id)\r\n-- from users\r\n-- group by creation_time ;"
    }
   ]
  },
  { "title": "Hi-C map DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Hi-C Maps",
   "type": "table",
   "description": "List of hi-c maps",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "select hi_c_maps.id, hi_c_maps.name, users.username\r\nfrom hi_c_maps\r\n    natural join users ;"
    }
   ]
  },
  {
   "title": "Hi-C maps count",
   "type": "stat",
   "description": "Number of hi-c maps",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(hi_c_maps.id)\r\nfrom hi_c_maps ;"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Server logs",
   "type": "logs",
   "description": "Server logs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"server-logs\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Server server attendance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({jobs=\"server-logs\"}[1h])"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Server logs errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({jobs=\"server-logs\"} | level = `ERROR` [1h])"
    }
   ]
  }
 ]
}