server:
  port: 8080
grpc:
  client:
    grpc-user-client-container:
      address: static://${SCHEDULER_HOST}:9090
      negotiation-type: plaintext

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}?currentSchema="public"&useUnicode=true&characterSetResults=UTF-8&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
        use_sql_comments: true
        format_sql: true

s3:
  url: http://${MINIO_HOST}:9000
  access:
    key: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
