auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    s3:
      endpoint: ${MINIO_HOST}:9000
      insecure: true
      bucketnames: loki-data,loki-data-copy
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      s3forcepathstyle: true
  replication_factor: 1
  ring:
    instance_addr: hict-logger-loki
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-12
      store: boltdb-shipper
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

limits_config:
  max_label_value_length: 10000

ruler:
  alertmanager_url: http://hict-promtail:9093
  storage:
    s3:
      bucketnames: loki-ruler
