apiVersion: 1

datasources:
- name: 'loki'
  type: 'loki'
  uid: 'ds_loki_id'
  url: 'http://hict-logger-loki:3100'
  access: 'proxy'
  is_default: true
  org_id: 1
  version: 1
  editable: false
- name: 'db_viewer'
  type: 'postgres'
  uid: 'ds_postgresql_viewer_id'
  url: '${POSTGRES_HOST}:5432'
  user: viewer
  secureJsonData:
    password: '${POSTGRES_VIEWER_PASSWORD}'
  jsonData:
    database: '${POSTGRES_DB}'
    sslmode: 'disable'
    maxOpenConns: 100
    maxIdleConns: 100
    maxIdleConnsAuto: true
    connMaxLifetime: 14400
    postgresVersion: 15000
    timescaledb: false
  access: 'proxy'
  is_default: true
  org_id: 3
  version: 1
  editable: false
